name: NontageLib
version: '1.0-SNAPSHOT'
api-version: '1.13'
main: top.nontage.nontagelib.NontageLib
authors: [ Nontage ]
description: A library for Nontage plugins
load: POSTWORLD
folia-supported: true
